name: linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev libx11-dev
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: ./build.sh
